### ISSUE TITLE
Is there going to be a new release marking the merge of the rewrite branch?

### ISSUE THREAD

**Issue by kinnairdclan** [wfg/docker-openvpn-client#101]
Just curious as a decent amount has landed in `master`. I have an idea of what needs changed to run master as opposed to `3.1.0` but just wanted to know if something was holding up tagging an official release. Thanks!

**Comment by wfg** [comment]
The last thing I want to do before tagging v4.0.0 is add a section in the README.md to guide users how to use this image with my dedicated [SOCKS5 server image](https://github.com/wfg/docker-socks5-server).

Since this merge cuts out the two proxies that were just kind of duct taped on, I want to give users a path forward.

**Comment by kinnairdclan** [comment]
Got it, thanks for the info much appreciated.
