### ISSUE TITLE
Please add DNS leak test script into the docker image

### ISSUE THREAD

**Issue by adr3nal1n** [wfg/docker-openvpn-client#55]
Hi,

I wanted to say a huge thank you for creating and maintaining this docker image, it is fantastic!

Can I suggest adding the dnsleaktest.sh script into your image (and store it in the data folder) from here https://github.com/macvk/dnsleaktest as this test, at least gives peace of mind that DNS is not leaking when connected to the VPN.

Note that the script requires curl, so you will need to "apk add curl" to your image for it to work.

This could then be added to your README as another test to Verify Functionality:
docker exec -it openvpn-client /data/dnsleaktest.sh

Thanks again for your excellent work.

**Comment by wfg** [comment]
I won't add that particular one. However, I'm not against the idea generally.

If you [look at that script](https://github.com/macvk/dnsleaktest/blob/master/dnsleaktest.sh#L102), you can see that it's just running a `curl` command and parsing the output. Since `wget` is already in the image, you should just use it.
```bash
docker exec openvpn-client wget -qO - "https://bash.ws/dnsleak/test/$(shuf -i 1000000-9999999 -n 1)?txt"
```

**Comment by adr3nal1n** [comment]
Ah yes I see, thanks for looking at this and for the instructions to use wget. I’ll use that going forwards.
